GEMINI_API_KEY = "AIzaSyBS2sovzdLbA076LsLLSjVPZveXPZOZuns"


[firebase]
type = "service_account"
project_id = "job-tracker-b3f0b"
private_key_id = "d3985f8224eadb889b0ce8bb9646298aeec01b45"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCn9sRb4V3+LYD7
21SNPMqDC1qzFxQxzbA7rcvrTXRjDJsmpJca+okHsbaYn+EdFLEdaMbkxKWhHCrQ
yQN27LFfJsJzVfRTL2z+jwpx2a1U2busUb+jd7yJb4RsTqC4PKXDY1tnQaG72+EZ
5QFMwC31bKosIZg3AJ//VEMuOrxWNbGtYBEWp6LBo7FXZEfrpGqGvlyyF4cDeeyf
CIXlI8N/6rS4QdUI8b1Q3um4APXhYui596OSuYLGTF4gGFW/WZMgnUvXtCPFDK39
qw3uSXLRUtaa0/aRhLT9GbB8ZXBVtNkxNgDwDKPktYex4dtA3QP3VBIRHJHxmWj0
wVrqn1lXAgMBAAECggEAO9L+TFWAg2xUsSAFRQr+fF9abkhNlpGS8CauZ4BecHsI
deKQuXi7vuRSy5jCdvesP/PWR5ws/C3KqDO4iq6yXFgzUR4v2EMfmKl9CGEGRh8J
I864KbKXkgII0gTNZOGhDu9AGo57WyxtSCpTZLFcjTongHF0xD5yPmCWTwx3kWKZ
yp7ATGv/Reu9ruSxI7fVIegzTTG5YHn5YkKaXJubwg1ZOOKjQrhK1RGQa2MLCCXU
xHF6OG5daVRroTe7/HCocH8m1RP44hVNWwZ5eVjmyD9JN8UX1Ukms+W3uobh5w/T
JX60Mnp1rMreRXNY4Yxfll2mAg/elDcZqhbnlNeHjQKBgQDSyOKQGkyrWMTfy5Sr
EC2JbYjWuGIwqTpEO4SrVrd9hV8i+bzHWBPUtTSl45JyRQD9v8HHjqaKLHP3PaaT
syrp2v6chkwKFcZpOKrezFSULQDYezGHAAc32Ye1Uawh8cJ8pnzlMZSHpkpGNc8I
Ly8OctsBK5aykIVJTd3v5xw1PQKBgQDL/mezvVzI68HgCw7xJsw+VprXPjE3NCaI
m+LdtQLWQT/BjuyJocJQlVf7+UmAP1KPMi8TEP4QYvIdYDu1tSl91cEVyAHZS8z5
E4yRmO9H0J8IFiqecAkAbmkmLsfMzxwEj2WPChMlNOj10apFc6gwWRQz6YsyEJxi
zS9Nmkl6IwKBgQCTFiMjM3b0yoj3MfSYOj3MfGbUju3VzwEdw/qcJXL9YCg3G9Yj
tM6By8DlUZxLqOM8LqdmPaDxInv5t0eaIZh8f5jUWNKO5wsBOc3ikusiSxUf+zdg
YSCoVF9io49eUHnKydK1jJd84QlLXRkPOP25M2SnuGb8S+T2diO82KTScQKBgHvW
OEwkE7ShcnO5ItwAipL5bkxmo+f4T8A0qhefcFZzC+pMAopW2aij0OLVZepmBo+J
joxLj4CRIJv2tKjNjp+maO35Gi441vkKBhbJOdFl83UsR7khGEXbwRd95KsPu9mE
18lq+05l/VplarF40cxv91TAXVEKRnWwTBwXIq3zAoGABnRxvxdFEsyzsX3ff1kE
E4JXegzHV5EpUtPyMF3vlXaAe3hTNpBLbgA+iAr+bF7tpKsFne/izMKbCrJLSN7B
yNGWrEilpmhLClyQKj5DlLT4LZOnHAjHmqAoHFxb7hMikwC8b6BsdRc/JNg9iFq6
lzDyI4Hz7zkmsYFN/3jNtrA=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@job-tracker-b3f0b.iam.gserviceaccount.com"
client_id = "103785057476993541810"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40job-tracker-b3f0b.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
